### PR TITLE
Update badges to point to JuliaMath

### PR DESCRIPTION
**Pull request by ararslan**
I've removed the AppVeyor badge for now since it's under a personal account and isn't pointing here. We'll have to have someone here add it to their account.

### CODE REVIEW

**Comment by ararslan** [comment]
Okay, also enabled Coveralls here.

**Comment by tkelman** [comment]
Did it get turned off? Might just have to re-enable it on the same account.

**Comment by ararslan** [comment]
I think the user whose account it was on would have to be an owner of this organization for that to work.

**Comment by ararslan** [comment]
I can put it on mine; I guess the stuff I have there now is pretty quiet.

**Comment by tkelman** [comment]
you don't need to be an owner usually, but you may need to set up the webhook manually if not

**Pull request merged**
